version: '3.7'
services:
  item-db:
    image: mongo:3
    restart: always
    ports:
    volumes:
      - app-db:/data/db

  item-app:
    image: wildanh/item-app:v1
    # command: npm install --production --unsafe-perm | npm run build
    depends_on:
      - item-db
    restart: always
    ports:
      - '80:8080'
volumes:
  app-db:
